// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs0YB6AnZ96RLSBc2HLgUaeA5B2HTDiFU',
    appId: '1:525148305676:web:ffc469f26b2556c6ad3129',
    messagingSenderId: '525148305676',
    projectId: 'testx-14f16',
    authDomain: 'testx-14f16.firebaseapp.com',
    storageBucket: 'testx-14f16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7XysOGlmnpF3q_7Bes3mVJtyWwVwaQ3E',
    appId: '1:525148305676:android:f307807235274813ad3129',
    messagingSenderId: '525148305676',
    projectId: 'testx-14f16',
    storageBucket: 'testx-14f16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx2Q_prxJCbGgR2Afb3hZAbSbX8z_GCZE',
    appId: '1:525148305676:ios:c0ee57d1eb008863ad3129',
    messagingSenderId: '525148305676',
    projectId: 'testx-14f16',
    storageBucket: 'testx-14f16.appspot.com',
    iosClientId: '525148305676-gis9sq78jf0rm3m0f80pt1o6u8dav8iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.testx',
  );
}
